modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/DaRealTurtyWurty/TurtyChemistry/issues"

[[mods]]
modId="turtychemistry"
version="1.0-DEV"
displayName="Turty's Chemistry"
updateJSONURL="https://raw.githubusercontent.com/DaRealTurtyWurty/TurtyChemistry/main/updates.json"
displayURL="https://github.com/DaRealTurtyWurty/TurtyChemistry/"
logoFile="logo.png"
credits="Steven (Textures), ilja615(Textures), Basti(Maths), SerialSniper(Maths) and finally people watching my Dev Streams who have both given me motivation and helped with things along the way."
authors="TurtyWurty"
description='''
A mod for minecraft which adds chemistry into the game.
'''