modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="turtychemistry"
version="1.0"
displayName="Turty's Chemistry"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
credits="TurtyWurty"
authors="TurtyWurty"
description='''

'''